package com.scenemax.desktop;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.apache.commons.io.FileUtils;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;

import java.awt.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.io.IOException;
import java.util.Locale;

import static javax.swing.JOptionPane.YES_OPTION;

public class PackageProgramDialog extends JDialog implements PropertyChangeListener {
    private JPanel contentPane;
    private JProgressBar progressBar1;
    private JLabel lblHeader1;
    private JButton buttonOK;
    private PackageProgramTask packageTask;
    private Runnable done;
    private String scriptFilePath;

    public PackageProgramDialog() {
        setContentPane(contentPane);
        setAlwaysOnTop(true);

    }

    private Runnable canceled = new Runnable() {
        @Override
        public void run() {

            setAlwaysOnTop(false);

            JOptionPane.showMessageDialog(
                    null,
                    "Program Packaging Failed",
                    "",
                    JOptionPane.ERROR_MESSAGE

            );

            PackageProgramDialog.this.dispose();
            done.run();

        }
    };

    private Runnable finished = new Runnable() {
        @Override
        public void run() {

            setAlwaysOnTop(false);
            String exeName = new File(PackageProgramDialog.this.scriptFilePath).getParentFile().getName();
            File exePath = new File(".\\build_games\\scenemax3d_scene.exe");
            int counter = 0;
            while (!exePath.exists()) {
                try {
                    Thread.sleep(500);
                    counter++;
                    if (counter > 6) {
                        break;
                    }
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }

            exeName = exeName.replace(" ", "_");
            File renameExePath = new File(".\\build_games\\" + exeName + ".exe");
            if (renameExePath.exists()) {
                renameExePath.delete();
            }

            try {
                FileUtils.moveFile(exePath, renameExePath);
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error renaming exe file.\r\nUsing the original file name: '" + exePath.getName() + "'");
                renameExePath = exePath;
            }

            int n = JOptionPane.showConfirmDialog(
                    null,
                    "Program packaging finished successfully. Open file location?",
                    "Open File Location",
                    JOptionPane.YES_NO_OPTION);

            if (n == YES_OPTION) {
                try {
                    Process p = new ProcessBuilder("explorer.exe", "/select,.\\build_games\\" + renameExePath.getName()).start();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }

            PackageProgramDialog.this.dispose();
            done.run();

        }
    };

    public void run(String scriptFilePath, String prg, final Runnable callback) {

        try {
            this.scriptFilePath = scriptFilePath;
            this.done = callback;
            packageTask = new PackageProgramTask(scriptFilePath, prg, this.finished, this.canceled);
            packageTask.addPropertyChangeListener(this);
            packageTask.execute();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        int progress = packageTask.getProgress();
        progressBar1.setValue(progress);
        progressBar1.updateUI();


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        progressBar1 = new JProgressBar();
        progressBar1.setStringPainted(true);
        panel1.add(progressBar1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblHeader1 = new JLabel();
        Font lblHeader1Font = this.$$$getFont$$$(null, -1, 18, lblHeader1.getFont());
        if (lblHeader1Font != null) lblHeader1.setFont(lblHeader1Font);
        lblHeader1.setText("Packaging program. Please wait...");
        panel1.add(lblHeader1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
