[workspace]
members = [
    "crates/assets",
    "crates/ir",
    "crates/multiplayer",
    "crates/parser",
    "crates/projector",
    "crates/runtime",
    "crates/runtime_script_core",
    "crates/runtime_ui_core",
]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.97"

[workspace.dependencies]
anyhow = "1"
avian3d = "0.7"
bevy-tnua = "0.32.0"
bevy-tnua-avian3d = "0.12.1"
bevy = { version = "0.19.0", default-features = false, features = ["3d", "bevy_ui", "bevy_ui_render", "bevy_text", "default_font", "bevy_sprite", "jpeg", "png"] }
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.dev]
opt-level = 1
debug = 1
incremental = true
codegen-units = 256

[profile.dev.package."*"]
opt-level = 1
debug = 0
codegen-units = 256

[profile.dev-perf]
inherits = "dev"

[profile.dev-perf.package."*"]
opt-level = 3
debug = 0
