[package]
name = "scenemax_runtime"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[features]
default = []
effekseer_native = ["dep:ash", "dep:wgpu"]

[dependencies]
anyhow.workspace = true
ash = { version = "0.38", optional = true }
avian3d.workspace = true
bevy.workspace = true
bevy-tnua.workspace = true
bevy-tnua-avian3d.workspace = true
scenemax_assets = { path = "../assets" }
scenemax_ir = { path = "../ir" }
scenemax_multiplayer = { path = "../multiplayer" }
scenemax_parser = { path = "../parser" }
scenemax_runtime_script_core = { path = "../runtime_script_core" }
scenemax_runtime_ui_core = { path = "../runtime_ui_core" }
scenemax_runtime_vm_core = { path = "../runtime_vm_core" }
serde = { workspace = true }
serde_json = { workspace = true }
tracing.workspace = true
wgpu = { version = "29.0.4", default-features = false, features = ["std", "vulkan", "dx12"], optional = true }
