[package]
name = "scenemax_ide"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
scenemax_assets = { path = "../../Common/assets" }
scenemax_materials = { path = "../../Engine/materials" }
scenemax_effects = { path = "../../Engine/effects", features = ["effekseer_native"] }
anyhow.workspace = true
serde_json.workspace = true
clap.workspace = true
bevy = { workspace = true, features = ["ui", "default_font", "system_font_discovery", "system_clipboard", "png", "jpeg", "3d", "audio", "wav"] }
scenemax_ide_core = { path = "../core" }
scenemax_ide_services = { path = "../services" }
scenemax_ide_ui = { path = "../ui" }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
